name: Deploy to Lightsail

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # htdocs 디렉토리 정리
            if [ ! -d "/opt/bitnami/apache2/htdocs/.git" ]; then
              # 기존 내용 백업
              sudo mv /opt/bitnami/apache2/htdocs /opt/bitnami/apache2/htdocs_backup_$(date +%Y%m%d_%H%M%S)
              # 새 디렉토리 생성
              sudo mkdir -p /opt/bitnami/apache2/htdocs
              # 권한 설정
              sudo chown -R $USER:daemon /opt/bitnami/apache2/htdocs
              # git clone
              cd /opt/bitnami/apache2
              git clone https://github.com/sootopia/lightsail-cicd.git htdocs
            else
              # 이미 저장소가 있는 경우 pull
              cd /opt/bitnami/apache2/htdocs
              git pull origin main
            fi
            # Apache 재시작
            sudo /opt/bitnami/ctlscript.sh restart apache